### ISSUE TITLE
Surface script doesn't work on Live 9.5

### ISSUE THREAD

**Issue by Fabmilan** [mpiraux/CMD-DC-1-Ableton-9-Control-Surface-Script#1]
Hi,

Firstable, thank you so much for your scripts.
Since Live 9.5, the script doesn't work. Do you have the same pb ?

Thank you.
Bye, Fab.

**Comment by mpiraux** [comment]
Hi!

That's curious because I've developed this script using Live 9.5 64bits on Windows. Then I assumed it'll also work for all versions after 9.1.4, which was the lastest big API change.
Could you be a bit more specific about your problem ? 
Is the script displayed in the drop down list ? (That means it compiles fine)
If so, when you click on it, does the view rectangle appear in session mode ? (That means it runs partially)
If so, what feature are missing ?

Could you please provide me the Ableton Log.txt file, which is really helpful in this situation.
It is located under: `/Users/-username-/Library/Preferences/Ableton/Live 9.x/` on Mac OSX.
And: `%appdata%/Ableton/Live/Preferences`

Thanks for your help, I could not test my script further than 9.5 on Windows, and your feedback will make it better :)

**Comment by Fabmilan** [comment]
Hey !

My mistake !

At first, I tried the script on this page Berhigner (http://origin.behringer.com/EN/products/CMD-DC-1.aspx). With this script, this was not compiled. So I found yours that worked and allowed me to see DC1 in the "Control Surface" . But I still do not see the rectange in the "session mode". And I don't know why, after a while I saw the rectangle. And it's work perfectly.

It's a mystery :)

Thx for your fast answer and for your script.
Bye !

**Comment by mpiraux** [comment]
From what I could see in my own Log.txt, there are still some errors reported by the script. Something like a unsigned integer being decremented below zero, but I could not determine if a feature was impacted by this bug. 
Anyway, keep reporting if something is going wrong according to you ;) 
As for now I'm closing this issue.
